# Generated by Django 5.2.5 on 2025-11-12 10:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'ordering': ['-created_at'], 'verbose_name': 'Велосипед', 'verbose_name_plural': 'Велосипеды'},
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_type',
            field=models.CharField(choices=[('mountain', 'Горный'), ('road', 'Шоссейный'), ('city', 'Городской'), ('electric', 'Электрический')], default='city', max_length=20, verbose_name='Тип велосипеда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='bike',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='bike',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за час'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('rented', 'Арендован'), ('maintenance', 'На обслуживании')], default='available', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='bike',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='BikeAtStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived_at', models.DateTimeField(auto_now_add=True, verbose_name='Прибыл на станцию')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.bike', verbose_name='Велосипед')),
            ],
            options={
                'verbose_name': 'Велосипед на станции',
                'verbose_name_plural': 'Велосипеды на станциях',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('id_number', models.CharField(max_length=50, verbose_name='Номер удостоверения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='RentalStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название станции')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('bikes', models.ManyToManyField(through='bike.BikeAtStation', to='bike.bike', verbose_name='Велосипеды')),
            ],
            options={
                'verbose_name': 'Станция аренды',
                'verbose_name_plural': 'Станции аренды',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.bike', verbose_name='Велосипед')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.customer', verbose_name='Клиент')),
                ('end_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_rentals', to='bike.rentalstation', verbose_name='Станция окончания')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_rentals', to='bike.rentalstation', verbose_name='Станция начала')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='bikeatstation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.rentalstation', verbose_name='Станция'),
        ),
        migrations.AlterUniqueTogether(
            name='bikeatstation',
            unique_together={('bike', 'station')},
        ),
    ]
