# Generated by Django 5.2.5 on 2025-11-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_alter_bike_options_bike_bike_type_bike_created_at_and_more'),
    ]

    operations = [
    ]
